import { nanoid } from "nanoid";
import {image1, image2, image3, image4, image5, image6, image7, image8, image9, image10, image11, image12, image13, image14, image15, image16, image17 } from"./images"

export const products = [
  {
    id: nanoid(),
    product: "Hoodie",
    price: 10,
    image: image1,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
  },
  {
    id: nanoid(),
    product: "Shoes",
    price: 10,
    image: image2,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
  },
  {
    id: nanoid(),
    product: "blouse",
    price: 10,
    image: image3,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
  },
  {
    id: nanoid(),
    product: "Jacket",
    price: 10,
    image: image4,
  },
  {
    id: nanoid(),
    product: "Hat",
    price: 10,
    image: image5,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
  },
   {
    id: nanoid(),
    product: "Hoodie",
    price: 10,
    image: image6,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
  },
  {
    id: nanoid(),
    product: "Shoes",
    price: 10,
    image: image7,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
  },
  {
    id: nanoid(),
    product: "blouse",
    price: 10,
    image: image8,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
  },
  {
    id: nanoid(),
    product: "Jacket",
    price: 10,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    image: image9,
  },
  {
    id: nanoid(),
    product: "Hat",
    price: 10,
    image: image10,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
  },
   {
    id: nanoid(),
    product: "Hoodie",
    price: 10,
    image: image11,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
  },
  {
    id: nanoid(),
    product: "Shoes",
    price: 10,
    image: image12,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
  },
  {
    id: nanoid(),
    product: "blouse",
    price: 10,
    image: image13,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
  },
  {
    id: nanoid(),
    product: "Jacket",
    price: 10,
    image: image14,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
  },
  {
    id: nanoid(),
    product: "Hat",
    price: 10,
    image: image15,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
  },
    {
    id: nanoid(),
    product: "Jacket",
    price: 10,
    image: image16,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
  },
  {
    id: nanoid(),
    product: "Hat",
    price: 10,
    image: image17,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
  },
];